#!/usr/bin/env bash

wdir="$(dirname $(git rev-parse --absolute-git-dir))"

for file in $wdir/flowchart/*.gv; do
    filename="${file##*/}"
    echo -n "Rendering file '$filename'... "
    dot -q1 -Tsvg $file -o $wdir/image/"${filename%.*}.svg"
    echo "done."
done
